# Generated by Django 5.2.7 on 2025-10-03 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('latency_ms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_identifier', models.CharField(db_index=True, max_length=255)),
                ('stage', models.CharField(choices=[('initial', 'Initial'), ('detailed', 'Detailed')], default='initial', max_length=20)),
                ('symptom_text', models.TextField(blank=True)),
                ('anxiety_score', models.FloatField(blank=True, null=True)),
                ('depression_score', models.FloatField(blank=True, null=True)),
                ('stress_score', models.FloatField(blank=True, null=True)),
                ('predicted_state', models.CharField(blank=True, max_length=100)),
                ('risk_level', models.CharField(blank=True, max_length=50)),
                ('recommendation', models.TextField(blank=True)),
                ('is_batch_processed', models.BooleanField(default=False)),
                ('follow_up_scheduled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_name', models.CharField(max_length=255)),
                ('submit_success', models.BooleanField(default=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_name', models.CharField(max_length=255)),
                ('metric_value', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
